name: ar_menu_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  dartz: 0.10.1 
  dio: ^5.1.2
  get_it: 7.2.0
  bloc: 8.1.0 
  flutter_bloc: 8.1.1 
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  zarinpal: ^1.0.5
  url_launcher: ^6.1.11
  uni_links: ^0.5.1
  loading_indicator: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.0




flutter:


  uses-material-design: true


  assets:
    - assets/images/



  fonts:
    - family: Tir
      fonts:
        - asset: assets/fonts/TIMESBD.ttf
